name: Las Vegas
favicon: null
layout_spectrum: 0.9713517150375992
typography_spectrum: 0.5142137531656772
title: Las Vegas 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3558488970156759
  lightness: 0.3156223245896399
  saturation: 0.2917897026054561
  rhythmicContrast: 0.7577189959120005
purpose: []
